# Generated by Django 4.2.4 on 2023-08-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
    ]
